import Head from 'next/head'
import React, { FC } from 'react'

interface Props {
  readonly title?: string
}

const MainLayout: FC<Props> = ({ children, title }) => {
  if (title) {
    return (
      <>
        <Head>
          <title>{title} | Noter</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main>{children}</main>
      </>
    )
  }

  return (
    <>
      <Head>
        <title>Noter</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>{children}</main>
    </>
  )
}

export default MainLayout
